### ISSUE TITLE
vue 3, sass-loader 11, TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by Twissi** [webpack-contrib/sass-loader#923]
- Operating System: macOS 11.2
- Node Version: v15.2.0
- NPM Version: npm v7.0.10
- webpack Version: 4.46.0
- sass-loader Version: 11.0.0
- vue: 3.0.0

### Expected Behavior

Start the vue 3 app without error.

### Actual Behavior

```
Syntax Error: TypeError: this.getOptions is not a function

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader-v16/dist/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=scss 4:14-419 14:3-18:5 15:22-427
 @ ./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=scss
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.176:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

### How Do We Reproduce?

```
$ vue create my-project (select vue 3 preview)
$ cd my-project
$ yarn add -D sass-loader sass
$ yarn serve
```

Works fine with sass-loader: 10.1.1

**Comment by alexander-akait** [comment]
You need webpack v5 to use latest version, please read CHANGELOG before updating

**Comment by Twissi** [comment]
@alexander-akait thanks!

**Comment by avenmore** [comment]
For Vue users, it seems that we will have to wait for the [release of Vue-cli v5.0.0](https://github.com/vuejs/vue-cli/releases) which [uses Webpack 5](https://next.cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service) before upgrading to version 11.x.

**Comment by Twissi** [comment]
> For Vue users, it seems that we will have to wait for the release of Vue-cli v5.0.0 which uses Webpack 5 before upgrading to version 11.x.

yes, that sounds right. I think until than many Vue users will run into the same issue when the add sass-loader by running `yarn add -D sass-loader sass` , because it will automatically install 11.x.

**Comment by symbioquine** [comment]
To summarize for others hitting this issue, install `sass-loader@10.1.1`;

```sh
npm install -D sass-loader@10.1.1 sass
```

**Comment by Mihai-github** [comment]
Hi,
    I have the above error and I know that I need the webpack v5 and still cannot get rid of the error. My current setup is:
"webpack": "5.53.0",
"node-sass": "^6.0.1",
"sass-loader": "12.1.0",
"sass": "^1.41.1".

Maybe someone has another way of solving this?

**Comment by alexander-akait** [comment]
@Mihai-github run `npm ls webpack`

**Comment by Mihai-github** [comment]
> @Mihai-github run `npm ls webpack`

Hi, 
   Thanks for your response. I've got after running the command you said this:

├─┬ react-scripts@4.0.3
│ └── webpack@4.44.2 
└── webpack@5.53.0

**Comment by alexander-akait** [comment]
As you can see you have two webpack versions and still on webpack v4

**Comment by Mihai-github** [comment]
Can you tell me please how can I get rid of the v4 ?

**Comment by alexander-akait** [comment]
@Mihai-github better to ask this in `react-scripts` repo

**Comment by Mihai-github** [comment]
ok, sure thank you :)
