### ISSUE TITLE
Regression in 0.3.0

### ISSUE THREAD

**Issue by appsforartists** [webpack-contrib/sass-loader#32]
I just tried upgrading to 0.3.0 and got this error in code that works in 0.2.0:

```
./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./application/styles.scss
Module build failed: TypeError: undefined is not a function
    at resolveSassPath (node_modules/sass-loader/node_modules/sass-graph/sass-graph.js:24:23)
    at Graph.addFile (node_modules/sass-loader/node_modules/sass-graph/sass-graph.js:66:20)
    at Graph.addFile (node_modules/sass-loader/node_modules/sass-graph/sass-graph.js:72:12)
    at Graph.addFile (node_modules/sass-loader/node_modules/sass-graph/sass-graph.js:72:12)
    at Object.module.exports.parseFile (node_modules/sass-loader/node_modules/sass-graph/sass-graph.js:122:9)
    at Object.module.exports (node_modules/sass-loader/index.js:33:27)
 @ ./application/styles.scss 3:1-339 8:9-347
```
