### ISSUE TITLE
Module build failed: TypeError: this.getResolve is not a function

### ISSUE THREAD

**Issue by FullStackZz** [webpack-contrib/sass-loader#753]
- Operating System: windows7
- Node Version: v8.9.3
- NPM Version: 5.5.1
- webpack Version: 3.6.0
- sass-loader Version: 8.0.0

### Expected Behavior
build success
build on sass-loader v7.3.1 no this error

### Actual Behavior
 ERROR  Failed to compile with 1 errors                                                                                                                                          12:33:44
 error  in ./src/components/docs/title/MdPage.vue

### **Module build failed: TypeError: this.getResolve is not a function**
    at Object.loader (E:\Studio\Record\ProjZz-DocsCenter\node_modules\sass-loader\dist\index.js:52:26)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0d714f71","scoped":false,"hasInline
Config":false}!./node_modules/sass-loader/dist/cjs.js?{"sourceMap":true}!./node_modules/vux-loader/src/style-loader.js!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./sr
c/components/docs/title/MdPage.vue 4:14-452 13:3-17:5 14:22-460
 @ ./src/components/docs/title/MdPage.vue

**Comment by evilebottnawi** [comment]
Please update webpack, you use old version, what is no supported

**Comment by jrester** [comment]
I am using webpack version 4.4.0 and Node on v10.16.0 and experience the same issue.

**Comment by evilebottnawi** [comment]
you need webpack@4.36.0

**Comment by thamizh-qwerty** [comment]
"webpack": "5.40.0" and "sass-loader": "12.1.0" -----> ModuleBuildError: Module build failed

**Comment by Rowna** [comment]
> 
I have "webpack": "^5.64.4" and "sass-loader": "^12.3.0", and I have the same probem"
What should I reunistall sass-loader or webpack to the updated version?

**Comment by jameelakowsar** [comment]
@Rowna , Did you found any solution, I am also facing same issue with you mentioned versions
